### ISSUE TITLE
Memory pre-allocation in LSTM

### ISSUE THREAD

**Issue by helson73** [harvardnlp/seq2seq-attn#70]
Hi, 
  I have a question about memory allocation in "make_lstm" function.
  In this function, memory dimension is defined like:
  `local RnnD={opt.rnn_size,opt.rnn_size}`
  And pre-allocations for some gates and transformations use this dimension.
  I am wondering, why batch_size is ignored in this case?
Thanks,
Li.

**Comment by helson73** [comment]
It should be 
`local RnnD={opt.max_batch_l, opt.rnn_size}`
right?

**Comment by helson73** [comment]
I am also wondering why output-dimension is ignored in some operations?
I found in "memory.lua", there is no schemes to handle missing output-dimension when Prealloc function is used.

**Comment by jsenellart-systran** [comment]
yes - for RnnD - but it actually does not change much - the preallocation main target is to share gradInput and output between the different clones. Their init size is overridden at the first cycle of backward/forward.
For output missing, it is on purpose - you can not for instance share output between clones for nn.Sigmoid, because backward is using output.

**Comment by helson73** [comment]
@jsenellart-systran Thanks, helped a lot.
